version: '3'

tasks:
  dev:
    desc: Run Hugo development server (CSS processed via PostCSS)
    cmds:
      - hugo server -D

  build:
    desc: Build for production
    cmds:
      - hugo --minify
